/**
 * Losing, but not buried. The register is different from `wrecked` on purpose:
 * this one still believes there is a way back, which is where the comedy is —
 * promised comebacks, small excuses, tactical analysis of nothing, and envy
 * badly disguised as sportsmanship.
 */
export const DOWN: string[] = [
  'Estoy a un buen tiro de volver.',
  'Voy perdiendo pero tengo un plan.',
  'Esto se da vuelta en dos filas.',
  'Me falta una sola buena y estamos.',
  'Vengo de atrás, es mi especialidad.',
  'No me gusta cómo viene, pero tampoco me asusta.',
  'Todavía no jugué mi mejor mano.',
  'Estoy midiendo al rival.',
  'Voy despacio a propósito.',
  'Guardé lo bueno para el final.',
  'Me está costando más de lo que esperaba.',
  'Hay partido, no se confíen.',
  'Un póker y volvemos a hablar.',
  'Estoy incómodo pero vivo.',
  'Me tocaron los peores tiros, es estadística.',
  'Nada que una generala no arregle.',
  'Todavía tengo filas buenas sin usar.',
  'Voy atrás pero no lejos.',
  'Esto recién empieza. Creo.',
  'Me falta suerte, no ganas.',
  'No es mi mejor día pero tampoco el peor.',
  'Estoy juntando bronca para el final.',
  'Me van a extrañar cuando remonte.',
  'Voy a necesitar un milagro chico.',
  'Estoy a tiro, dejen de festejar.',
  'Perdiendo se aprende. Estoy aprendiendo mucho.',
  'La suerte tiene que darse vuelta en algún momento.',
  'Me guardé las buenas para las últimas.',
  'Estoy peor de lo que me gustaría admitir.',
  'Falta mucho, tranquilos.',
  'No es la diferencia, es la sensación.',
  'Estoy jugando de contragolpe.',
  'Un descuido y los alcanzo.',
  'Voy a hacer como que esto es parte del plan.',
  'Me sobra partido.',
  'Todavía no me preocupo.',
  'Bueno, ahora sí me preocupo un poco.',
  'Necesito que se distraigan cinco minutos.',
  'Me falta un envión.',
  'Estoy en el momento aburrido de mi remontada.',
  'La diferencia es menos de lo que parece.',
  'Voy a empezar a jugar en serio ahora.',
  'Ya me pasó estar así y salí. Una vez.',
  'Me está faltando un poco de todo.',
  'Tengo fe y poco más.',
  'Se me está haciendo cuesta arriba.',
  'Nada grave, nada bueno tampoco.',
  'Estoy en zona de riesgo.',
  'Todavía puedo, no me entierren.',
  'Me hace falta una fila grande.',
  'Voy segundo, que es primero de los que pierden.',
  'Esto se define en las últimas.',
  'Me tienen donde quieren, pero no por mucho.',
  'Voy a cambiar de estrategia. No tenía, pero igual.',
  'Estoy a un golpe de suerte de ser insoportable.',
  'Perder así molesta más que perder feo.',
  'Me tocó el peor tramo.',
  'No estoy contento pero estoy entero.',
  'Falta poco y estoy lejos. Mala combinación.',
  'Un par de tiros y les cambio la cara.',
  'Estoy calculando, no me apuren.',
  'Ya me pasó y ya lo di vuelta.',
  'Cambiá la energía de la mesa, por favor.',
  'Me hace falta que alguien tache.',
  'Estoy esperando mi momento.',
  'Confío en el desorden del universo.',
  'La estadística me tiene que devolver algo.',
  'Voy atrás pero jugando bien. Miento.',
  'Necesito que alguien más también pierda.',
  'Estoy incómodo con el marcador.',
  'Voy a pedir un cambio de dados.',
  'Esto se puede arreglar todavía.',
  'Me estoy quedando sin filas buenas.',
  'Falta una sola cosa y no sé cuál.',
  'Voy perdiendo por poco, que es peor.',
  'Estoy en el limbo de la planilla.',
  'Hoy la suerte reparte mal.',
  'Un empujón y estoy arriba.',
  'No es para tanto todavía.',
  'Me molesta más de lo que muestro.',
  'Estoy jugando a no perder, que ya es algo.',
  'Voy a aguantar hasta que se cansen.',
  'Me falta una generala y dos milagros.',
  'Estoy a mitad de camino de ningún lado.',
  'La cosa está fea pero no perdida.',
  'Sigo en carrera, de última.',
  'Me estoy poniendo nervioso y no me gusta.',
  'Que nadie se relaje todavía.',
  'Voy a remontar de una forma humillante para ustedes.',
  'Estoy peor que hace dos filas.',
  'Necesito concentrarme y me distraen.',
  'Perdiendo pero con dignidad.',
  'Me falta un poco de fortuna, nada más.',
  'Voy a fingir confianza a ver si funciona.',
  'La remontada empieza ahora. O ahora. O ahora.',
  'Estoy juntando fuerzas.',
  'No me está saliendo nada y sonrío igual.',
  'Todavía tengo con qué.',
  'Falta, pero se puede.',
  'Estoy a una buena de estar bien.',
]
