/**
 * Running away with it, and no longer pretending otherwise. The register is
 * arrogance, condescending generosity and acceptance speeches given far too
 * early — the person at the table nobody wants to be sitting across from.
 */
export const ECSTATIC: string[] = [
  'Esto ya está, no se esfuercen.',
  'Quiero agradecer a los dados.',
  'Alguien anote bien esta partida.',
  'Estoy en un nivel distinto hoy.',
  'Pidan la hora.',
  'Me da un poco de pena, en serio.',
  'Esto lo voy a contar por años.',
  'Que alguien filme esto.',
  'Voy a permitirme disfrutarlo.',
  'No es soberbia, es información.',
  'Estoy jugando el mejor partido de mi vida.',
  'Que se preparen para la próxima también.',
  'Hoy no me gana nadie.',
  'Voy tan arriba que se ve el horizonte.',
  'Esta partida ya está. Vayan pensando en la revancha.',
  'Los dados me quieren y se nota.',
  'Esto es una demostración.',
  'Estoy imparable y lo sé.',
  'Que alguien me pare, por favor. Es un decir.',
  'Voy a extrañar esta sensación.',
  'Me sale absolutamente todo.',
  'Esto se terminó hace rato.',
  'Estoy en modo leyenda.',
  'Quiero dedicarle esta partida a mí.',
  'No hay con qué darme hoy.',
  'Voy a hacer de cuenta que fue difícil.',
  'Estoy demasiado arriba, es incómodo.',
  'Me estoy divirtiendo mucho, ustedes no.',
  'Esto ya es abuso.',
  'Voy arriba por mucho y por mérito.',
  'Que nadie se ofenda pero era obvio.',
  'Estoy tocando el cielo con las manos.',
  'La partida es mía desde el principio.',
  'Me siento invencible y es un problema.',
  'Voy a guardar esta planilla de recuerdo.',
  'Esto no es suerte, es superioridad.',
  'Que aprendan mirando.',
  'Estoy jugando en otro plano.',
  'Voy tan bien que da vergüenza ajena.',
  'Me tengo que contener para no festejar.',
  'Esto es una clase magistral.',
  'Voy a dejar que anoten un poco para no aburrirme.',
  'Estoy arrasando con elegancia.',
  'Que alguien les explique cómo se juega.',
  'Voy ganando y todavía no jugué en serio.',
  'Me está saliendo hasta lo que no intento.',
  'Esto ya no tiene emoción.',
  'Estoy en la cima y hay buena vista.',
  'Voy a necesitar una vitrina.',
  'Me da lástima el resto de la mesa.',
  'Esto es lo más cerca de la perfección que estuve.',
  'Voy a hablar de esto en las próximas cenas.',
  'Estoy en una nube.',
  'Que se resignen tranquilos.',
  'No me van a alcanzar ni queriendo.',
  'Voy a fingir modestia en tres, dos, uno.',
  'Estoy jugando con el piloto puesto y gano igual.',
  'Esto es humillante para ustedes y hermoso para mí.',
  'Voy arriba por goleada.',
  'Me siento en el mejor día de mi vida.',
  'Que nadie me despierte.',
  'Estoy haciendo historia en esta mesa.',
  'Voy a ganar y voy a hablar mucho.',
  'Esto se define solo.',
  'Estoy tan bien que desconfío.',
  'Me tocó todo y lo aproveché todo.',
  'Voy tan arriba que ya no hay competencia.',
  'Que alguien anote la fecha.',
  'Estoy en una racha histórica.',
  'Voy a disfrutar cada fila que queda.',
  'Me sobra partida.',
  'Esto es un paseo.',
  'Estoy arriba de todo y de todos.',
  'Voy a extrañar ganar así.',
  'Que preparen las excusas.',
  'Estoy jugando perfecto.',
  'No me alcanzan ni con dos turnos extra.',
  'Voy a recordar esta partida con cariño.',
  'Estoy insoportable y me lo gané.',
  'Que se prepare el que quiera revancha.',
  'Voy tan arriba que ya no compito.',
  'Me sale todo de primera.',
  'Esto es lo que pasa cuando uno sabe.',
  'Estoy en estado de gracia.',
  'Voy a ganar cómodo y con onda.',
  'Que alguien me diga que esto es real.',
  'Estoy tocando la gloria.',
  'Voy adelante por una distancia grosera.',
  'Me siento imparable.',
  'Esto ya lo gané, falta el papeleo.',
  'Estoy en el mejor momento de la noche.',
  'Voy a disfrutar el silencio de la mesa.',
  'Que nadie diga que no avisé.',
  'Estoy volando.',
  'Voy holgadísimo y ni me despeiné.',
  'Me estoy luciendo y me encanta.',
  'Esto es superioridad pura.',
  'Estoy ganando de una forma ofensiva.',
  'Voy a poner esta planilla en el living.',
  'Que se acostumbren.',
  'Estoy imbatible hoy.',
]
