/**
 * Nobody is running away with it. The hardest of the five to write, because
 * "nothing is happening" is not a feeling — so these are about everything
 * EXCEPT the score: boredom, hunger, the room, the person who takes too long
 * to throw. That is what a level player actually thinks about.
 */
export const LEVEL: string[] = [
  'Estoy igual que todos y eso me inquieta.',
  'Ni bien ni mal. Existiendo.',
  'Esto está muy parejo para mi gusto.',
  'Tengo hambre, sinceramente.',
  'Estoy esperando que pase algo.',
  'Se está jugando raro hoy.',
  'Nada para reportar.',
  'Voy en el medio, como siempre.',
  'Estoy tranquilo, que es sospechoso.',
  'Alguien tiene que romper el empate.',
  'Me aburre estar cómodo.',
  'Sin novedad en la planilla.',
  'Estoy pensando en otra cosa.',
  'Que alguien haga algo, por favor.',
  'Vamos parejos y eso pone nervioso.',
  'No estoy ni contento ni triste.',
  'Estoy en modo ahorro de energía.',
  'Esto se define después.',
  'Vengo administrando.',
  'Estoy esperando mi momento sin apuro.',
  'Me falta emoción.',
  'Todo bien, todo normal, todo aburrido.',
  'Está muy tranquila la mesa.',
  'Alguien ponga música.',
  'Estoy en piloto automático.',
  'Ni me despeinaron ni despeiné.',
  'Voy a esperar a que se equivoquen.',
  'Esto está muy correcto para ser divertido.',
  'Me distraje y no pasó nada.',
  'La partida está sin dueño.',
  'Estoy neutro y voy a seguir así un rato.',
  'Cualquiera puede ganar esto.',
  'Prefiero ir perdiendo, al menos se siente algo.',
  'Estoy ahorrando reacciones.',
  'Voy justo en el medio, como me gusta no estar.',
  'Nadie se está destacando, incluido yo.',
  'Estoy cómodo y desconfío.',
  'Falta que alguien se mande una locura.',
  'Se está haciendo largo.',
  'Estoy esperando la fila que decida todo.',
  'Sin sobresaltos por ahora.',
  'Esto podría terminar de cualquier manera.',
  'Voy bien, voy mal, va igual.',
  'Estoy en el limbo.',
  'Me gustaría tener algo para decir.',
  'La planilla está aburrida.',
  'Estoy jugando sin convicción.',
  'Todo bajo control, o nada bajo control.',
  'Estoy en pausa.',
  'Que empiece el partido de verdad.',
  'Nada me sale mal, nada me sale bien.',
  'Voy en piloto.',
  'Estoy esperando un motivo para emocionarme.',
  'Ni fu ni fa.',
  'Falta que alguien la rompa.',
  'Estoy manteniendo el tipo.',
  'No sé si voy ganando o perdiendo, sinceramente.',
  'Se está poniendo interesante. Mentira.',
  'Estoy administrando la nada.',
  'Voy a mirar el techo un rato.',
  'Alguien apure el tiro.',
  'Estoy pensando en qué comer después.',
  'La partida está empatada y yo también.',
  'Sin emociones fuertes hasta ahora.',
  'Estoy jugando con la mente en otro lado.',
  'Todo parejo, todo tibio.',
  'Estoy esperando la sorpresa.',
  'Se me está yendo la concentración.',
  'Voy igual que hace cinco filas.',
  'Estoy en tierra de nadie.',
  'Ni me entusiasmo ni me deprimo.',
  'Falta chispa en esta mesa.',
  'Estoy en el medio de la tabla y de la vida.',
  'Que alguien tache algo importante.',
  'Voy tranquilo, casi dormido.',
  'Estoy cómodo pero sin gracia.',
  'La cosa está pareja, para variar.',
  'Me falta un poco de drama.',
  'Estoy jugando sin ganas ni desgano.',
  'Voy a esperar sentado.',
  'Todo igual desde hace rato.',
  'Estoy sin noticias.',
  'Se juega mucho y pasa poco.',
  'Estoy expectante, o algo así.',
  'Voy parejo con todos y eso me da igual.',
  'Estoy esperando que se defina solo.',
  'La partida no arranca.',
  'Estoy en modo neutral.',
  'Nada emocionante hasta ahora.',
  'Voy a hacer tiempo.',
  'Estoy sin opinión formada.',
  'Todo tranquilo por acá.',
  'Me falta una razón para festejar o quejarme.',
  'Estoy a mitad de todo.',
  'Se está definiendo en cámara lenta.',
  'Voy sin sobresaltos.',
  'Estoy en la mitad exacta de la nada.',
  'Que pase algo, cualquier cosa.',
  'Estoy bien, gracias por preguntar.',
  'Nada que declarar.',
  'Sigo acá, esperando.',
]
