/**
 * Winning, but not by enough to gloat outright — and that gap is the joke.
 * These are the lines of somebody trying very hard to look modest: false
 * humility, advice nobody asked for, and superstition about not jinxing it.
 */
export const PLEASED: string[] = [
  'Voy bien y no lo quiero decir en voz alta.',
  'Tranquilo, dominando.',
  'No quiero adelantarme pero voy adelante.',
  'Está saliendo todo bastante bien.',
  'No es suerte, es oficio. Bueno, un poco de suerte.',
  'Voy arriba y me hago el distraído.',
  'La cosa viene encaminada.',
  'No canto victoria, pero la tarareo.',
  'Me está saliendo lo que quiero.',
  'Voy cómodo sin exagerar.',
  'Que nadie diga nada para no arruinarlo.',
  'Estoy en un buen momento.',
  'La planilla me está tratando bien.',
  'Voy primero y me siento raro.',
  'Todo según lo planeado.',
  'No es mi mejor partida y voy ganando igual.',
  'Estoy en control de la situación.',
  'Me gusta cómo viene esto.',
  'No festejo todavía, falta.',
  'Voy sobrado pero educado.',
  'Estoy jugando con paciencia.',
  'Se está dando lo que esperaba.',
  'Voy tranquilo y eso los pone nerviosos.',
  'La suerte y yo estamos en buenos términos.',
  'Estoy contento y trato de disimularlo.',
  'Vengo bien, no quiero mufarme.',
  'Todo bajo control por ahora.',
  'Voy arriba sin hacer ruido.',
  'Me está saliendo casi todo.',
  'Estoy en mi mejor versión de hoy.',
  'La ventaja es cómoda, no definitiva.',
  'Voy ganando y sé que no alcanza.',
  'Estoy jugando relajado.',
  'Me tocaron buenos tiros y los aproveché.',
  'No es para tanto. Bueno, un poco sí.',
  'Voy primero y pienso quedarme.',
  'Todo tranquilo desde acá arriba.',
  'Estoy administrando la ventaja.',
  'Me siento bien parado.',
  'Voy bien y no quiero hablar de más.',
  'Estoy en racha y no lo voy a nombrar.',
  'La cosa está de mi lado.',
  'Voy adelante y me lo estoy creyendo un poco.',
  'Estoy jugando sin sobresaltos.',
  'Me está yendo mejor de lo que merezco.',
  'Todo va saliendo.',
  'Voy arriba y me guardo los comentarios.',
  'Estoy tranquilo, que es lo peligroso.',
  'La ventaja está, falta sostenerla.',
  'Me siento sólido.',
  'Voy ganando de manera aburrida, como me gusta.',
  'Estoy contento sin festejar.',
  'La partida va por donde quiero.',
  'Voy bien y no me voy a confiar.',
  'Estoy en un momento dulce.',
  'Me sale todo lo que intento.',
  'Voy arriba y todavía tengo filas buenas.',
  'Estoy jugando cómodo.',
  'No es una paliza, es una diferencia.',
  'Voy primero por ahora, que es lo que cuenta.',
  'Estoy satisfecho con lo que hice.',
  'La ventaja no es enorme pero es mía.',
  'Voy bien y me lo disfruto en silencio.',
  'Estoy con confianza.',
  'Me está saliendo la mano.',
  'Voy arriba sin despeinarme.',
  'Estoy jugando a mi ritmo.',
  'Todo bien por acá, gracias.',
  'La cosa viene de dulce.',
  'Voy adelante y no pienso aflojar.',
  'Estoy contento y me falta poco.',
  'Me gusta este lugar de la planilla.',
  'Voy ganando y no quiero decirlo.',
  'Estoy en ventaja, no en victoria.',
  'La mano me viene acompañando.',
  'Voy bien y ya lo estoy anticipando.',
  'Estoy en el buen lado del marcador.',
  'Me está funcionando la estrategia.',
  'Voy primero y me hago el humilde.',
  'Estoy jugando con margen.',
  'La ventaja tranquiliza.',
  'Voy bien y no lo quiero arruinar.',
  'Estoy en un lugar cómodo.',
  'Me sale lo que necesito cuando lo necesito.',
  'Voy adelante, sin ventilador.',
  'Estoy contento y lo escondo mal.',
  'La partida está de mi lado.',
  'Voy arriba y todavía falta.',
  'Estoy tranquilo y enfocado.',
  'Me viene saliendo bien la cosa.',
  'Voy ganando y me río por dentro.',
  'Estoy en ventaja y con ganas de más.',
  'La ventaja da para relajarse un poco.',
  'Voy bien y no quiero hablar todavía.',
  'Estoy jugando fino.',
  'Me sobra un poco de todo.',
  'Voy adelante y me lo merezco.',
  'Estoy en mi mejor tramo.',
  'La cosa pinta bien.',
  'Voy ganando, con permiso.',
  'Estoy bien, muy bien, pero no lo digo.',
]
