/**
 * Mood at the bottom of the scale: buried, and knows it.
 *
 * First person, present tense, short enough to read in the second the modal is
 * open. The comedy is denial, blame and melodrama — never self-pity played
 * straight, which stops being funny on the second reading.
 *
 * Nothing in here names a player, a score or a game. These are moods, not
 * verdicts: verdicts.ts is where the lines that quote real numbers live, and
 * it can only do that because it is handed the numbers. A line here that said
 * "voy 90 abajo" would be a guess.
 */
export const WRECKED: string[] = [
  'Estoy para el descarte.',
  'Los dados me odian y no lo disimulan.',
  'Vine a acompañar, aparentemente.',
  'Alguien revise esos dados, en serio.',
  'Esto ya no es un partido, es una autopsia.',
  'Me estoy replanteando muchas cosas.',
  'A este paso el helado lo termino pagando yo.',
  'Estoy jugando otro juego y nadie me avisó.',
  'Ya no juego para ganar, juego para terminar.',
  'Toqué fondo y seguí cavando.',
  'Mi mejor jugada fue sentarme.',
  'Nunca vi el fondo de la tabla tan de cerca.',
  'Aguanto porque irme sería peor.',
  'Vengo a hacer bulto.',
  'Esto tiene explicación pero no la voy a dar.',
  'La suerte está en otra mesa.',
  'Anotá tranquilo, total ya está.',
  'Cada tiro es una noticia peor.',
  'No puedo caer más bajo. Lo dije la mano pasada también.',
  'Sigo acá por orgullo y por nada más.',
  'Los dados y yo dejamos de hablarnos.',
  'Ya perdí, solo falta el trámite.',
  'Que alguien me tire una soga.',
  'No es mala suerte, es persecución.',
  'Perdí temprano y me quedé por educación.',
  'Estoy en modo espectador.',
  'Me estoy riendo para no llorar.',
  'Vine con expectativas. Craso error.',
  'La planilla es un documento hostil.',
  'Que conste que empecé bien.',
  'Nadie me avisó que se jugaba en serio.',
  'Este es mi peor momento del año.',
  'Voy a necesitar un rato solo después.',
  'La dignidad la perdí hace un rato largo.',
  'Alguien cambió los dados, es la única.',
  'Estoy compitiendo conmigo mismo y perdiendo.',
  'Que se apuren, quiero que termine.',
  'Ya me arrepentí de haber venido.',
  'Mi estrategia falló en todos los frentes.',
  'Estoy tocando un piso nuevo.',
  'Esto no es un bajón, es un derrumbe.',
  'La mesa se ríe y tiene razón.',
  'Perdí, pero perdí con estilo. Mentira.',
  'Ni tachando me sale bien.',
  'Me estoy tomando esto peor de lo que debería.',
  'Alguien anote que jugué bajo protesta.',
  'Estoy pensando en mudarme de mesa.',
  'Es matemáticamente triste.',
  'Ya ni miro los dados cuando caen.',
  'Hoy no era. Ayer tampoco.',
  'Vine a perder y estoy cumpliendo.',
  'Necesito un abrazo y una revancha.',
  'Me quedé sin excusas nuevas.',
  'Esto es un castigo por algo que hice.',
  'Todo lo que podía salir mal ya salió.',
  'Que no me pregunten nada, gracias.',
  'Perdí la fe en el azar.',
  'Estoy aprendiendo mucho. De humildad.',
  'Cada vez que tiro, empeoro.',
  'Se me nota en la cara y no lo puedo evitar.',
  'Estoy en el peor lugar de la planilla.',
  'Que alguien me explique qué pasó.',
  'Empecé mal y desde ahí bajé.',
  'Mi único aporte es el contraste.',
  'Hago que los otros se sientan buenos.',
  'Vine a ser el ejemplo de lo que no hay que hacer.',
  'Ya me da lo mismo qué salga.',
  'Estoy jugando en modo tributo.',
  'Perdí antes de empezar y no me di cuenta.',
  'Esto se me fue de las manos rápido.',
  'Alguien apague la luz cuando termine.',
  'Me estoy quedando sin ganas.',
  'La remontada era en otro momento.',
  'Que no me hablen de estrategia ahora.',
  'Estoy mal, pero mal mal.',
  'Ni el mejor tiro me arregla esto.',
  'Me rindo, pero en silencio.',
  'Voy a fingir que esto no está pasando.',
  'Estoy pasando por una etapa.',
  'Que quede en esta mesa, por favor.',
  'No cuenten esta partida.',
  'Voy a pedir que se anule.',
  'Esto es un bochorno deportivo.',
  'Perdí hasta las ganas de tachar.',
  'Ya me estoy imaginando la revancha.',
  'Necesito que esto termine ya.',
  'Estoy jugando de memoria y me falla la memoria.',
  'Toqué el fondo del fondo.',
  'Que alguien me saque de acá.',
  'Creí que había tocado fondo y me equivoqué.',
  'Ni con trampa llego.',
  'Se me cayó el mundo y todavía lo estoy juntando.',
  'Sigo respirando, que ya es algo.',
  'Que nadie me mire, gracias.',
  'Voy a hacer como que esto es un ensayo.',
  'No hay lectura positiva de esto.',
  'Estoy compitiendo por el último puesto y voy ganando.',
  'La suerte me soltó la mano en la primera.',
  'Esto ya es maltrato.',
  'Que se termine y hablamos.',
]
